# Generated by Django 4.0.5 on 2022-06-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название поля')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес поля')),
                ('size', models.CharField(max_length=256, verbose_name='Размеры поля')),
                ('gate', models.PositiveIntegerField(verbose_name='Количество ворот')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('location', models.TextField(verbose_name='Локация')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
        ),
    ]
