# Generated by Django 4.0.5 on 2022-06-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='is_active',
            field=models.BooleanField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
