# Generated by Django 4.0.5 on 2022-06-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_hello_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='is_active',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
