# Generated by Django 4.0.5 on 2022-06-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_hello_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hello',
            options={'verbose_name': 'Start message', 'verbose_name_plural': 'Start messages'},
        ),
        migrations.AlterField(
            model_name='hello',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
