# Generated by Django 4.0.5 on 2022-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_footballfield_options_imageforfootballfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('key', models.CharField(max_length=130, unique=True, verbose_name='Ключ')),
                ('value', models.CharField(blank=True, max_length=210, verbose_name='Значение')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватная настройка')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Найстройки',
            },
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.AlterModelOptions(
            name='imageforfootballfield',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
