# Generated by Django 4.0.5 on 2022-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_alter_footballfield_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforfootballfield',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
